indicators:
  - key: "INDICATOR_LAST_TOTAL"
    description: "Total Last Month Visits"
    indicatorQuery: "
      select count (*)
      from ( select distinct(base_entity_id), date(datetime(visit_date/1000, 'unixepoch')) as date_visited
      from visits
      where datetime(visit_date/1000, 'unixepoch') < date('now', 'start of month') and datetime(visit_date/1000, 'unixepoch') > date('now', 'start of month', '-1 months')
      and visit_type in ('Other Member ADDO Visit', 'Adolescent ADDO Visit', 'ANC ADDO Visit', 'PNC ADDO Visit', 'Child ADDO Visit' )
      group by base_entity_id, date_visited )"